import type { ArchitecturePlan } from "./architectureEngine.js";
import { architectureSummary } from "./architectureEngine.js";
import type { GeneratedFile } from "./types.js";

export function generateDocumentation(
  plan: ArchitecturePlan,
  stats: { fileCount: number; moduleCount: number }
): { files: GeneratedFile[]; docs: { path: string; title: string }[] } {
  const root = plan.projectName;
  const files: GeneratedFile[] = [];
  const docs: { path: string; title: string }[] = [];

  const readme = `# ${plan.projectName}

Enterprise Katalon automation framework generated by **AI Katalon Project Generator**.

## Architecture

- **Type:** ${plan.frameworkKind}
- **Pattern:** ${plan.architecturePattern}
- **Domain:** ${plan.domain}
- **Summary:** ${architectureSummary(plan)}

## Structure

\`\`\`
${root}/
├── Object Repository/   # Semantic OR with healing metadata
├── Keywords/            # Reusable custom keywords
├── pages/               # Page Object Model classes
├── api/                 # API clients, auth, validators
├── mobile/              # Appium mobile pages
├── performance/         # k6 + JMeter scaffolds
├── Test Cases/          # Modular test scripts
├── Test Suites/         # Smoke, sanity, regression
├── docs/                # Architecture documentation
└── ai/                  # AI memory & healing hints
\`\`\`

## Modules

${plan.modules.map((m) => `- ${m}`).join("\n")}

## Business flows

${plan.flows.map((f) => `- ${f}`).join("\n")}

## Getting started

1. Import this project into Katalon Studio.
2. Update \`Profiles/default.glbl\` with environment URLs.
3. Run **Smoke_Suite** first, then expand regression coverage.

Generated files: **${stats.fileCount}** · Modules: **${stats.moduleCount}**
`;

  files.push({
    path: `${root}/README.md`,
    kind: "doc",
    content: readme,
    summary: "Project README",
  });
  docs.push({ path: "README.md", title: "Project README" });

  const archDoc = `# Architecture — ${plan.projectName}

## Layers

${plan.layers.map((l) => `- \`${l}\``).join("\n")}

## Design principles

- Page Object Model with OR-backed locators
- Keyword-driven reusable services
- No raw Selenium — Katalon WebUI/Mobile/WS APIs only
- Self-healing metadata on Object Repository entries
- Enterprise naming prefix: **${plan.namingPrefix}**

## Reporting

${plan.includeReporting ? "Extent-style logging via ExtentReportHelper keyword." : "Standard Katalon reports under Reports/."}

## AI integration

See \`ai/project-memory-hints.json\` for style conventions applied during generation.
`;

  files.push({
    path: `${root}/docs/ARCHITECTURE.md`,
    kind: "doc",
    content: archDoc,
  });
  docs.push({ path: "docs/ARCHITECTURE.md", title: "Architecture" });

  files.push({
    path: `${root}/docs/SUITES.md`,
    kind: "doc",
    content: `# Test Suites\n\n| Suite | Purpose |\n|-------|--------|\n| Smoke_Suite | Fast critical checks |\n| Sanity_Suite | Core module validation |\n| Regression_Suite | Full module coverage |\n| Critical_Path_Suite | Highest business risk flows |\n`,
  });
  docs.push({ path: "docs/SUITES.md", title: "Suite documentation" });

  return { files, docs };
}
