import type { ArchitecturePlan } from "./architectureEngine.js";
import type { GeneratedFile } from "./types.js";

const BASE_FOLDERS = [
  "Object Repository",
  "Keywords",
  "Scripts",
  "Test Cases",
  "Test Suites",
  "Test Listeners",
  "Include",
  "Profiles",
  "Data Files",
  "Reports",
  "settings",
  "docs",
  "api",
  "pages",
  "utils",
  "performance",
  "mobile",
  "ai",
];

export function scaffoldProjectTree(plan: ArchitecturePlan): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const root = plan.projectName;

  for (const folder of BASE_FOLDERS) {
    files.push({
      path: `${root}/${folder}/.gitkeep`,
      kind: "config",
      content: "",
      summary: `Scaffold folder: ${folder}`,
    });
  }

  files.push({
    path: `${root}/settings/internal/com.kms.katalon.core.webservice.properties`,
    kind: "config",
    content: `# Generated by AI Katalon Project Generator\n`,
  });

  files.push({
    path: `${root}/Profiles/default.glbl`,
    kind: "profile",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<GlobalVariableEntities>
  <description>Default environment profile — ${plan.projectName}</description>
  <name>default</name>
  <tag></tag>
  <defaultProfile>true</defaultProfile>
  <GlobalVariableEntity>
    <description>Base URL for web tests</description>
    <initValue>https://example.com</initValue>
    <name>baseUrl</name>
    <protected>false</protected>
    <valueType>STRING</valueType>
  </GlobalVariableEntity>
  <GlobalVariableEntity>
    <description>API base URL</description>
    <initValue>https://api.example.com</initValue>
    <name>apiBaseUrl</name>
    <protected>false</protected>
    <valueType>STRING</valueType>
  </GlobalVariableEntity>
</GlobalVariableEntities>
`,
    summary: "Default global profile with baseUrl and apiBaseUrl",
  });

  return files;
}
