import type { ProjectIndex } from "../projectIntelligence/types.js";
import { loadProjectIndex } from "../projectIntelligence/projectStore.js";
import {
  buildMemoryContextForGeneration,
  resolveAiMemoryMode,
  shouldInjectMemory,
} from "../aiMemory/index.js";
import { enrichEndpointsInPlace, groupBySemanticModule } from "../apiArchitect/index.js";
import type { ApiEndpointSpec, ApiCodegenResult, ApiGeneratorOptions, AuthType, GeneratedGroovyFile } from "./types.js";
import {
  listRequestObjectPaths,
  matchProjectRequestObject,
  toRequestObjectPath,
} from "./requestObjectBuilder.js";
import { generateSchemaAssertions, schemaAssertionSummary } from "./schemaAssertionGenerator.js";
import { generateNegativeTestsForAll } from "./negativeTestGenerator.js";
import { generateBoundaryTestsForAll } from "./boundaryTestGenerator.js";
import { generateAllHelperFiles } from "./apiHelperGenerator.js";
import { UniqueVarNames, endpointVarPrefix, emitGroovyMapLiteral } from "./groovyEmit.js";

function pascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
    .join("");
}

const TEST_SCRIPT_IMPORTS = [
  "import com.kms.katalon.core.testobject.RequestObject",
  "import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS",
  "import com.kms.katalon.core.model.FailureHandling",
  "import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject",
  "import internal.GlobalVariable as GlobalVariable",
  "import api.ApiRequestBuilder",
  "import api.ApiPayloadBuilder",
  "import api.ResponseValidator",
];

function buildHappyPathTest(
  endpoint: ApiEndpointSpec,
  requestPath: string,
  styleHint: string | null,
  vars: UniqueVarNames
): string[] {
  const responseVar = vars.response("Success");
  const requestVar = vars.request("Success");
  const lines = [
    "",
    `// === [${endpoint.semanticModule ?? "API"}] ${endpoint.businessAction ?? endpoint.name} ===`,
    `// ${endpoint.method} ${endpoint.path}`,
  ];
  if (styleHint) lines.push(`// Team style: ${styleHint.slice(0, 120)}`);

  if (endpoint.requestBodyExample && Object.keys(endpoint.requestBodyExample).length > 0) {
    const payloadVar = vars.payload("Success");
    lines.push(
      `Map ${payloadVar} = ${emitGroovyMapLiteral(endpoint.requestBodyExample)}`,
      `RequestObject ${requestVar} = ApiRequestBuilder.prepare('${requestPath}')`,
      `${requestVar} = ApiPayloadBuilder.withBody(${requestVar}, ${payloadVar})`,
      `def ${responseVar} = ApiRequestBuilder.send(${requestVar}, ${endpoint.successStatus ?? 200})`
    );
  } else {
    lines.push(
      `RequestObject ${requestVar} = ApiRequestBuilder.prepare('${requestPath}')`,
      `def ${responseVar} = ApiRequestBuilder.send(${requestVar}, ${endpoint.successStatus ?? 200})`
    );
  }

  const tokenField =
    endpoint.responseFields?.find((f) => /token|access_token|jwt/i.test(f)) ??
    (endpoint.responseExample && "token" in endpoint.responseExample ? "token" : null);

  if (tokenField) {
    lines.push(
      `def expectedToken = ${responseVar}.getPropertyValue('${tokenField}')`,
      `assert expectedToken : 'Response must include ${tokenField}'`,
      `ResponseValidator.assertJsonField(${responseVar}, '${tokenField}', expectedToken)`,
      `GlobalVariable.apiToken = expectedToken`
    );
  }

  const schemaLines = generateSchemaAssertions(endpoint);
  for (const line of schemaLines) {
    lines.push(line.replace(/\bresponse\b/g, responseVar));
  }

  lines.push(`ResponseValidator.assertResponseTime(${responseVar}, 5000)`);
  return lines;
}

function detectPrimaryAuth(endpoints: ApiEndpointSpec[]): AuthType {
  return endpoints.find((e) => e.auth && e.auth !== "none")?.auth ?? "none";
}

function buildTestScriptFile(
  endpoints: ApiEndpointSpec[],
  requestPathById: Map<string, string>,
  options: {
    testName: string;
    auth: AuthType;
    styleHint: string | null;
    includeNegative: boolean;
    includeBoundary: boolean;
  }
): { content: string; negativeTitles: string[]; boundaryTitles: string[] } {
  const suiteName = pascalCase(options.testName);
  const body: string[] = [
    ...TEST_SCRIPT_IMPORTS,
    "",
    `// Scripts/API/${suiteName}Tests.groovy`,
    `// Generated by API Test — ${new Date().toISOString().slice(0, 10)}`,
    `// Uses Keywords/api/* helpers — import api.* or add Keywords to classpath`,
    "// Never hardcode secrets — use GlobalVariable and execution profiles",
    "",
    `def ${suiteName}Tests() {`,
  ];

  const varsByEndpoint = new Map<string, UniqueVarNames>();

  for (const ep of endpoints) {
    const path = requestPathById.get(ep.id)!;
    const vars = new UniqueVarNames(endpointVarPrefix(ep.name));
    varsByEndpoint.set(ep.id, vars);
    body.push(...buildHappyPathTest(ep, path, options.styleHint, vars));
  }

  let negativeTitles: string[] = [];
  let boundaryTitles: string[] = [];

  if (options.includeNegative) {
    const neg = generateNegativeTestsForAll(endpoints, requestPathById, varsByEndpoint);
    body.push("", "// ========== Negative tests (mutated payloads) ==========");
    body.push(...neg.groovyFragments);
    negativeTitles = neg.titles;
  }

  if (options.includeBoundary) {
    const bnd = generateBoundaryTestsForAll(endpoints, requestPathById, varsByEndpoint);
    body.push("", "// ========== Boundary tests (mutated payloads) ==========");
    body.push(...bnd.groovyFragments);
    boundaryTitles = bnd.titles;
  }

  body.push("}");

  return {
    content: body.join("\n"),
    negativeTitles,
    boundaryTitles,
  };
}

export async function generateApiCode(
  endpoints: ApiEndpointSpec[],
  options: ApiGeneratorOptions = {},
  parseWarnings: string[] = []
): Promise<ApiCodegenResult> {
  if (!endpoints.length) {
    throw new Error("No API endpoints to generate");
  }

  enrichEndpointsInPlace(endpoints);
  const warnings = [...parseWarnings];
  let index: ProjectIndex | null = null;
  if (options.projectId) {
    try {
      index = await loadProjectIndex(options.projectId);
    } catch {
      warnings.push(`Project ${options.projectId} not found — using default RequestObject paths`);
    }
  }

  const requestPathById = new Map<string, string>();
  for (const ep of endpoints) {
    const reused = matchProjectRequestObject(ep, index);
    if (reused) {
      requestPathById.set(ep.id, reused);
      warnings.push(`Reusing project RequestObject for ${ep.name}: ${reused}`);
    } else {
      requestPathById.set(ep.id, toRequestObjectPath(ep));
    }
  }

  const auth = detectPrimaryAuth(endpoints);
  const memoryMode = resolveAiMemoryMode(options.aiMemoryMode);
  let styleHint: string | null = null;
  if (options.projectId && index && shouldInjectMemory(memoryMode)) {
    const steps = endpoints.map((e) => `${e.method} ${e.path}`);
    const ctx = await buildMemoryContextForGeneration(options.projectId, steps, index, memoryMode);
    if (ctx?.injectionText) styleHint = ctx.injectionText.slice(0, 200);
  }

  const testName = options.testCaseName?.trim() || "ApiTestSuite";
  const includeNegative = options.includeNegative !== false;
  const includeBoundary = options.includeBoundary !== false;

  const modules = groupBySemanticModule(endpoints);
  const scriptFiles: GeneratedGroovyFile[] = [];
  let negativeTitles: string[] = [];
  let boundaryTitles: string[] = [];
  let primaryScript = "";

  if (modules.size > 1) {
    for (const [moduleName, eps] of modules) {
      const modName = pascalCase(moduleName.replace(/[^a-zA-Z0-9]/g, " "));
      const built = buildTestScriptFile(eps, requestPathById, {
        testName: modName,
        auth,
        styleHint,
        includeNegative,
        includeBoundary,
      });
      scriptFiles.push({ path: `Scripts/API/${modName}Tests.groovy`, kind: "script", content: built.content });
      negativeTitles.push(...built.negativeTitles);
      boundaryTitles.push(...built.boundaryTitles);
      if (!primaryScript) primaryScript = built.content;
    }
    warnings.push(`Split test scripts by semantic module: ${[...modules.keys()].join(", ")}`);
  } else {
    const built = buildTestScriptFile(endpoints, requestPathById, {
      testName,
      auth,
      styleHint,
      includeNegative,
      includeBoundary,
    });
    primaryScript = built.content;
    negativeTitles = built.negativeTitles;
    boundaryTitles = built.boundaryTitles;
    scriptFiles.push({
      path: `Scripts/API/${pascalCase(testName)}Tests.groovy`,
      kind: "script",
      content: built.content,
    });
  }

  const helperFiles = options.includeHelpers !== false ? generateAllHelperFiles(auth) : [];
  const files: GeneratedGroovyFile[] = [...helperFiles, ...scriptFiles];

  const requestObjects = listRequestObjectPaths(endpoints, index);
  const schemaAssertions = schemaAssertionSummary(endpoints);

  warnings.push(
    "Add Keywords under Keywords/api/ (ApiPayloadBuilder, ApiRequestBuilder, ResponseValidator, TokenManager).",
    "Each test calls ApiRequestBuilder.prepare() for a fresh RequestObject before payload mutation."
  );

  return {
    groovyCode: primaryScript,
    files,
    requestObjects,
    schemaAssertions,
    negativeTests: negativeTitles,
    boundaryTests: boundaryTitles,
    reusableHelpers: helperFiles.map((f) => f.path),
    warnings,
    preview: {
      endpoints: endpoints.map((e) => ({
        method: e.method,
        path: e.path,
        name: e.businessAction ?? e.name,
        auth: e.auth,
      })),
      authType: auth,
      validationStrategy:
        "Semantic modules + ApiPayloadBuilder.withBody + ResponseValidator (status, schema, response time)",
      semanticModules: [...new Set(endpoints.map((e) => e.semanticModule).filter(Boolean))] as string[],
      scenarioCount:
        endpoints.length +
        (includeNegative ? negativeTitles.length : 0) +
        (includeBoundary ? boundaryTitles.length : 0),
    },
  };
}
