export const SENIOR_QA_ENGINEER_NAME = "Gosi Brain";
export const SENIOR_QA_ENGINEER_TITLE = "QA Director";
export const SENIOR_QA_ENGINEER_DISPLAY = `${SENIOR_QA_ENGINEER_NAME} — ${SENIOR_QA_ENGINEER_TITLE}`;
